name: Deploy to Firebase

on:
  push:
    branches:
      - build/firebase
jobs:
  build:
    name: Building and distributing app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      
      
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Bundle the app
        run: npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

      - name: Set Gradlew Permissions
        run: chmod +x android/gradlew

      - name: Build application
        run: |
          cd ./android
          ./gradlew assembleDebug

      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload artifact to Firebase App Distribution
        id: testing_outputs
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Print all outputs of the previous step
        run: |
          echo ${{steps.testing_outputs.outputs.FIREBASE_CONSOLE_URI}}
          echo ${{steps.testing_outputs.outputs.TESTING_URI}}
          echo ${{steps.testing_outputs.outputs.BINARY_DOWNLOAD_URI}}